name: Full CI/CD for .NET App

on:
  #manual run
  workflow_dispatch:
  #on pushing main branch on folder 'api'
  push:
    branches:
      - 'main'
    paths:
      - 'api/**'
env:
  WEBAPP_NAME: dotNetConf
  RESOURCE_GROUP: dotNetConf
  SLOT_NAME: staging

jobs:
  build:
    name: Build and push docker image
    runs-on: ubuntu-latest
    steps:
      #checkout
      - name: 'Checkout GitHub Action'
        uses: actions/checkout@master

      # login
      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{secrets.DOCKERHUB_USERNAME}}
          password: ${{secrets.DOCKERHUB_TOKEN}}

      #build and push docker image
      - name: Build and push docker image
        run: |
          cd ./api
          docker build -t niazovd/product-service:${{github.sha}} .
          docker push niazovd/product-service:${{github.sha}}

  staging:
    name: Deploy staging
    needs: build
    runs-on: ubuntu-latest
    steps:
      #login to Azure with service principal
      - name: Login via Azure CLI
        uses: azure/login@v1
        with:
          cred: ${{secrets.AZURE_CREDENTIALS}}

      #deploy image to Azure App Service
      - name: Deploy to staging environment
        uses: azure/webapps-deploy@v2
        with:
          app-name: ${{ env.WEBAPP_NAME }}
          slot-name: ${{ env.SLOT_NAME }}
          images: 'niazovd/product-service:${{ github.sha }}'
