name: Full CI/CD for .NET App

on:
  workflow_dispatch:
  push:
    branches:
      - 'main'
    paths:
      - 'api/**'
jobs:
  #buildAndPublish
  build:
    name: Build and publish docker image
    runs-on: ubuntu-latest #agent
    steps:
      #checkout
      - name: Checkout
        uses: actions/checkout@main
      #login to DockerHub
      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secret.DOCKERHUB_USERNAME}}
          password: ${{ secret.DOCKERHUB_TOKEN}}

      #buildAndPush
      - name: Build and push Docker image
        run: |
          cd ./api
          docker build -t niazovd/product-service:${{ github.sha }}
          docker push niazovd/product-service:${{ github.sha }}
