name: Full CI/CD for .NET App

on:
  #manual run
  workflow_dispatch:
  #on pushing main branch on folder 'api'
  push:
    branches:
      - 'main'
    paths:
      - 'api/**'

jobs:
  build:
    name: Build and push docker image
    runs-on: ubuntu-latest
    steps:
      #checkout
      - name: 'Checkout GitHub Action'
        uses: actions/checkout@master

      # login
      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{secrets.DOCKERHUB_USERNAME}}
          password: ${{secrets.DOCKERHUB_TOKEN}}

      #build and push docker image
      - name: Build and push docker image
        run: |
          cd ./api
          docker build -t niazovd/product-service:${{github.sha}} .
          docker push niazovd/product-service:${{github.sha}}
