name: Full CI/CD for .NET App

on:
  workflow_dispatch:
  push:
    branches:
      - 'main'
    paths:
      - 'api/**'
env:
  WEBAPP_NAME: dotNetConf
  SLOT_NAME: staging

jobs:
  #buildAndPublish
  build:
    name: Build and publish docker image
    runs-on: ubuntu-latest #agent
    steps:
      #checkout
      - name: Checkout
        uses: actions/checkout@main
      #login to DockerHub
      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME}}
          password: ${{ secrets.DOCKERHUB_TOKEN}}

      #buildAndPush
      - name: Build and push Docker image
        run: |
          cd ./api
          docker build -t niazovd/product-service:${{ github.sha }} .
          docker push niazovd/product-service:${{ github.sha }}
  staging:
    name: Deploy staging
    needs: build
    runs-on: ubuntu-latest
    steps:
      #login to Azure CLI
      - name: Login to Azure CLI
        uses: azure/login@v1
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }} #uses service principal

      #deploy to dotNetConf-staging
      - name: Deploy to staging environment
        uses: azure/webapps-deploy@v2
        with:
          app-name: ${{ env.WEBAPP_NAME }}
          slot-name: ${{ env.SLOT_NAME }}
          images: niazovd/product-service:${{ github.sha }}
  
  production:
    name: Deploy production
    needs: staging
    runs-on: ubuntu-latest
    environment:
      name: 'production'
      url: 'https://${{ env.WEBAPP_NAME }}.azurewebsites.net/'
    steps:
      - name: Login to Azure CLI
        uses: azure/login@v1
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }} #uses service principal
      
      #swap staging with production
      - name: Deploy production
        run: az webapp deployment slot swap -s ${{ env.SLOT_NAME }} -n ${{ env.WEBAPP_NAME }} -g dotNetConf  
