name: CI CD

on:
  workflow_dispatch:
  push:
    branches:
      - 'main'
    paths:
      - api/**

env:
  WEBAPP_NAME: dotNetConf
  RESOURCE_GROUP: dotNetConf
  SLOT_NAME: staging

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: 'Checkout Github Action'
        uses: actions/checkout@master

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - run: |
          cd ./api
          docker build . -t niazovd/product-service:${{ github.sha }}
          docker push niazovd/product-service:${{ github.sha }}

  staging:
    name: Deploy Staging
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: 'Login via Azure CLI'
        uses: azure/login@v1
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}

      - name: Deploy to staging environment
        uses: azure/webapps-deploy@v2
        with:
          app-name: ${{ env.WEBAPP_NAME }}
          slot-name: 'staging'
          images: 'niazovd/product-service:${{ github.sha }}'

  production:
    name: Deploy to production
    needs: staging
    runs-on: ubuntu-latest
    environment:
      name: 'production'
      url: 'https://${{ env.WEBAPP_NAME }}.azurewebsites.net/'

    steps:
      - name: Log into Azure CLI with service principal
        uses: azure/login@v1.1
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}

      - name: Swap slots
        run: az webapp deployment slot swap -s ${{ env.SLOT_NAME }} -n ${{ env.WEBAPP_NAME }} -g ${{ env.RESOURCE_GROUP }}
